pipeline {
    agent any
    stages {
        stage('Submit Stack') {
            steps {
              sh "cat ./devopscourse-main/01_s3cft.yml"
              sh "aws cloudformation create-stack --stack-name s3bucket --template-body file://devopscourse-main/01_s3cft.yml --region 'us-east-1'"
              }
             }
            }
            }
